stages:
  - test
  - lint


find name test:
  stage: test
  script:
    - chmod +x find-word.sh
    - ./find-word.sh


yamllint:
  stage: lint
  image: python:3.9
  before_script:
    - pip install yamllint
  script:
    - yamllint --fix .
  only:
    - branches
    - commit

